#PORT
server:
  port: ${env.SERVER_PORT}
#  ssl:
#    key-store-type: ${env.SSL_KEY}
#    key-store: ${env.SSL_KEYSTORE}
#    key-store-password: ${env.SSL_KEYSTORE_PASSWORD}
#    key-alias: ${env.SSL_ALIAS}

#Database config
spring:
  application:
    name: AgroCare
  jpa:
    hibernate:
      naming:
        physical-strategy: ${env.PHYSICAL_STRATEGY}
      ddl-auto: ${env.HIBERNATE_DDL}
    show-sql: true
    properties:
      hibernate:
        dialect: ${env.HIBERNATE_DIALECT}
        use_sql_comments: true
        format_sql: true
  datasource:
    name: ${env.DATABASE_NAME}
    url: jdbc:mysql://${env.DATABASE_HOST}/${env.DATABASE_NAME}?createDatabaseIfNotExist=true
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}
    driver-class-name: ${env.DATABASE_DRIVER}

JWT_SECRET: ${env.JWT_SECRET}