#PORT
server:
  port: 9000

#Database config
spring:
  application:
    name: AgroCare
  jpa:
    hibernate:
      naming:
        physical-strategy: com.agrocare.agrocare.configuration.other.CamelCasePhysicalNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        format_sql: true
  datasource:
    name: AgroCare
    url: jdbc:mysql://localhost:3306/AgroCare?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
